[project]
name = "fluxer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "entsoe-py>=0.7.0",
    "jupyter>=1.1.1",
    "pandas>=2.3.1",
]
