library(data.table)

tz_table = data.table(
  zone = c(
    "DE_50HZ",
    "AL",
    "DE_AMPRION",
    "AT",
    "BY",
    "BE",
    "BA",
    "BG",
    "CZ_DE_SK",
    "HR",
    "CWE",
    "CY",
    "CZ",
    "DE_AT_LU",
    "DE_LU",
    "DK",
    "DK_1",
    "DK_1_NO_1",
    "DK_2",
    "DK_CA",
    "EE",
    "FI",
    "MK",
    "FR",
    "DE",
    "GR",
    "HU",
    "IS",
    "IE_SEM",
    "IE",
    "IT",
    "IT_SACO_AC",
    "IT_CALA",
    "IT_SACO_DC",
    "IT_BRNN",
    "IT_CNOR",
    "IT_CSUD",
    "IT_FOGN",
    "IT_GR",
    "IT_MACRO_NORTH",
    "IT_MACRO_SOUTH",
    "IT_MALTA",
    "IT_NORD",
    "IT_NORD_AT",
    "IT_NORD_CH",
    "IT_NORD_FR",
    "IT_NORD_SI",
    "IT_PRGP",
    "IT_ROSN",
    "IT_SARD",
    "IT_SICI",
    "IT_SUD",
    "RU_KGD",
    "LV",
    "LT",
    "LU",
    "LU_BZN",
    "MT",
    "ME",
    "GB",
    "GE",
    "GB_IFA",
    "GB_IFA2",
    "GB_ELECLINK",
    "UK",
    "NL",
    "NO_1",
    "NO_1A",
    "NO_2",
    "NO_2_NSL",
    "NO_2A",
    "NO_3",
    "NO_4",
    "NO_5",
    "NO",
    "PL_CZ",
    "PL",
    "PT",
    "MD",
    "RO",
    "RU",
    "SE_1",
    "SE_2",
    "SE_3",
    "SE_4",
    "RS",
    "SK",
    "SI",
    "GB_NIR",
    "ES",
    "SE",
    "CH",
    "DE_TENNET",
    "DE_TRANSNET",
    "TR",
    "UA",
    "UA_DOBTPP",
    "UA_BEI",
    "UA_IPS",
    "XK",
    "DE_AMP_LU"
  ),
  eic = c(
    "10YDE-VE-------2",
    "10YAL-KESH-----5",
    "10YDE-RWENET---I",
    "10YAT-APG------L",
    "10Y1001A1001A51S",
    "10YBE----------2",
    "10YBA-JPCC-----D",
    "10YCA-BULGARIA-R",
    "10YDOM-CZ-DE-SKK",
    "10YHR-HEP------M",
    "10YDOM-REGION-1V",
    "10YCY-1001A0003J",
    "10YCZ-CEPS-----N",
    "10Y1001A1001A63L",
    "10Y1001A1001A82H",
    "10Y1001A1001A65H",
    "10YDK-1--------W",
    "46Y000000000007M",
    "10YDK-2--------M",
    "10Y1001A1001A796",
    "10Y1001A1001A39I",
    "10YFI-1--------U",
    "10YMK-MEPSO----8",
    "10YFR-RTE------C",
    "10Y1001A1001A83F",
    "10YGR-HTSO-----Y",
    "10YHU-MAVIR----U",
    "IS",
    "10Y1001A1001A59C",
    "10YIE-1001A00010",
    "10YIT-GRTN-----B",
    "10Y1001A1001A885",
    "10Y1001C--00096J",
    "10Y1001A1001A893",
    "10Y1001A1001A699",
    "10Y1001A1001A70O",
    "10Y1001A1001A71M",
    "10Y1001A1001A72K",
    "10Y1001A1001A66F",
    "10Y1001A1001A84D",
    "10Y1001A1001A85B",
    "10Y1001A1001A877",
    "10Y1001A1001A73I",
    "10Y1001A1001A80L",
    "10Y1001A1001A68B",
    "10Y1001A1001A81J",
    "10Y1001A1001A67D",
    "10Y1001A1001A76C",
    "10Y1001A1001A77A",
    "10Y1001A1001A74G",
    "10Y1001A1001A75E",
    "10Y1001A1001A788",
    "10Y1001A1001A50U",
    "10YLV-1001A00074",
    "10YLT-1001A0008Q",
    "10YLU-CEGEDEL-NQ",
    "10Y1001A1001A82H",
    "10Y1001A1001A93C",
    "10YCS-CG-TSO---S",
    "10YGB----------A",
    "10Y1001A1001B012",
    "10Y1001C--00098F",
    "17Y0000009369493",
    "11Y0-0000-0265-K",
    "10Y1001A1001A92E",
    "10YNL----------L",
    "10YNO-1--------2",
    "10Y1001A1001A64J",
    "10YNO-2--------T",
    "50Y0JVU59B4JWQCU",
    "10Y1001C--001219",
    "10YNO-3--------J",
    "10YNO-4--------9",
    "10Y1001A1001A48H",
    "10YNO-0--------C",
    "10YDOM-1001A082L",
    "10YPL-AREA-----S",
    "10YPT-REN------W",
    "10Y1001A1001A990",
    "10YRO-TEL------P",
    "10Y1001A1001A49F",
    "10Y1001A1001A44P",
    "10Y1001A1001A45N",
    "10Y1001A1001A46L",
    "10Y1001A1001A47J",
    "10YCS-SERBIATSOV",
    "10YSK-SEPS-----K",
    "10YSI-ELES-----O",
    "10Y1001A1001A016",
    "10YES-REE------0",
    "10YSE-1--------K",
    "10YCH-SWISSGRIDZ",
    "10YDE-EON------1",
    "10YDE-ENBW-----N",
    "10YTR-TEIAS----W",
    "10Y1001C--00003F",
    "10Y1001A1001A869",
    "10YUA-WEPS-----0",
    "10Y1001C--000182",
    "10Y1001C--00100H",
    "10Y1001C--00002H"
  ),
  description = c(
    "50Hertz CA, DE(50HzT) BZA",
    "Albania, OST BZ / CA / MBA",
    "Amprion CA",
    "Austria, APG BZ / CA / MBA",
    "Belarus BZ / CA / MBA",
    "Belgium, Elia BZ / CA / MBA",
    "Bosnia Herzegovina, NOS BiH BZ / CA / MBA",
    "Bulgaria, ESO BZ / CA / MBA",
    "BZ CZ+DE+SK BZ / BZA",
    "Croatia, HOPS BZ / CA / MBA",
    "CWE Region",
    "Cyprus, Cyprus TSO BZ / CA / MBA",
    "Czech Republic, CEPS BZ / CA/ MBA",
    "DE-AT-LU BZ",
    "DE-LU BZ / MBA",
    "Denmark",
    "DK1 BZ / MBA",
    "DK1 NO1 BZ",
    "DK2 BZ / MBA",
    "Denmark, Energinet CA",
    "Estonia, Elering BZ / CA / MBA",
    "Finland, Fingrid BZ / CA / MBA",
    "Former Yugoslav Republic of Macedonia, MEPSO BZ / CA / MBA",
    "France, RTE BZ / CA / MBA",
    "Germany",
    "Greece, IPTO BZ / CA/ MBA",
    "Hungary, MAVIR CA / BZ / MBA",
    "Iceland",
    "Ireland (SEM) BZ / MBA",
    "Ireland, EirGrid CA",
    "Italy, IT CA / MBA",
    "Italy_Saco_AC",
    "IT-Calabria BZ",
    "Italy_Saco_DC",
    "IT-Brindisi BZ",
    "IT-Centre-North BZ",
    "IT-Centre-South BZ",
    "IT-Foggia BZ",
    "IT-GR BZ",
    "IT-MACROZONE NORTH MBA",
    "IT-MACROZONE SOUTH MBA",
    "IT-Malta BZ",
    "IT-North BZ",
    "IT-North-AT BZ",
    "IT-North-CH BZ",
    "IT-North-FR BZ",
    "IT-North-SI BZ",
    "IT-Priolo BZ",
    "IT-Rossano BZ",
    "IT-Sardinia BZ",
    "IT-Sicily BZ",
    "IT-South BZ",
    "Kaliningrad BZ / CA / MBA",
    "Latvia, AST BZ / CA / MBA",
    "Lithuania, Litgrid BZ / CA / MBA",
    "Luxembourg, CREOS CA",
    "Luxembourg",
    "Malta, Malta BZ / CA / MBA",
    "Montenegro, CGES BZ / CA / MBA",
    "National Grid BZ / CA/ MBA",
    "Georgia",
    "GB(IFA) BZN",
    "GB(IFA2) BZ",
    "GB(ElecLink) BZN",
    "United Kingdom",
    "Netherlands, TenneT NL BZ / CA/ MBA",
    "NO1 BZ / MBA",
    "NO1 A BZ",
    "NO2 BZ / MBA",
    "NO2 NSL BZ / MBA",
    "NO2 A BZ",
    "NO3 BZ / MBA",
    "NO4 BZ / MBA",
    "NO5 BZ / MBA",
    "Norway, Norway MBA, Stattnet CA",
    "PL-CZ BZA / CA",
    "Poland, PSE SA BZ / BZA / CA / MBA",
    "Portugal, REN BZ / CA / MBA",
    "Republic of Moldova, Moldelectica BZ/CA/MBA",
    "Romania, Transelectrica BZ / CA/ MBA",
    "Russia BZ / CA / MBA",
    "SE1 BZ / MBA",
    "SE2 BZ / MBA",
    "SE3 BZ / MBA",
    "SE4 BZ / MBA",
    "Serbia, EMS BZ / CA / MBA",
    "Slovakia, SEPS BZ / CA / MBA",
    "Slovenia, ELES BZ / CA / MBA",
    "Northern Ireland, SONI CA",
    "Spain, REE BZ / CA / MBA",
    "Sweden, Sweden MBA, SvK CA",
    "Switzerland, Swissgrid BZ / CA / MBA",
    "TenneT GER CA",
    "TransnetBW CA",
    "Turkey BZ / CA / MBA",
    "Ukraine, Ukraine BZ, MBA",
    "Ukraine-DobTPP CTA",
    "Ukraine BEI CTA",
    "Ukraine IPS CTA",
    "Kosovo/ XK CA / XK BZN",
    "Amprion LU CA"
  ),
  tz = c(
    "Europe/Berlin",
    "Europe/Tirane",
    "Europe/Berlin",
    "Europe/Vienna",
    "Europe/Minsk",
    "Europe/Brussels",
    "Europe/Sarajevo",
    "Europe/Sofia",
    "Europe/Prague",
    "Europe/Zagreb",
    "Europe/Brussels",
    "Asia/Nicosia",
    "Europe/Prague",
    "Europe/Berlin",
    "Europe/Berlin",
    "Europe/Copenhagen",
    "Europe/Copenhagen",
    "Europe/Copenhagen",
    "Europe/Copenhagen",
    "Europe/Copenhagen",
    "Europe/Tallinn",
    "Europe/Helsinki",
    "Europe/Skopje",
    "Europe/Paris",
    "Europe/Berlin",
    "Europe/Athens",
    "Europe/Budapest",
    "Atlantic/Reykjavik",
    "Europe/Dublin",
    "Europe/Dublin",
    "Europe/Rome",
    "Europe/Rome",
    "Europe/Rome",
    "Europe/Rome",
    "Europe/Rome",
    "Europe/Rome",
    "Europe/Rome",
    "Europe/Rome",
    "Europe/Rome",
    "Europe/Rome",
    "Europe/Rome",
    "Europe/Rome",
    "Europe/Rome",
    "Europe/Rome",
    "Europe/Rome",
    "Europe/Rome",
    "Europe/Rome",
    "Europe/Rome",
    "Europe/Rome",
    "Europe/Rome",
    "Europe/Kaliningrad",
    "Europe/Riga",
    "Europe/Vilnius",
    "Europe/Luxembourg",
    "Europe/Luxembourg",
    "Europe/Malta",
    "Europe/Podgorica",
    "Europe/London",
    "Asia/Tbilisi",
    "Europe/London",
    "Europe/London",
    "Europe/London",
    "Europe/London",
    "Europe/Amsterdam",
    "Europe/Oslo",
    "Europe/Oslo",
    "Europe/Oslo",
    "Europe/Oslo",
    "Europe/Oslo",
    "Europe/Oslo",
    "Europe/Oslo",
    "Europe/Oslo",
    "Europe/Oslo",
    "Europe/Warsaw",
    "Europe/Warsaw",
    "Europe/Lisbon",
    "Europe/Chisinau",
    "Europe/Bucharest",
    "Europe/Moscow",
    "Europe/Stockholm",
    "Europe/Stockholm",
    "Europe/Stockholm",
    "Europe/Stockholm",
    "Europe/Belgrade",
    "Europe/Bratislava",
    "Europe/Ljubljana",
    "Europe/Belfast",
    "Europe/Madrid",
    "Europe/Stockholm",
    "Europe/Zurich",
    "Europe/Berlin",
    "Europe/Berlin",
    "Europe/Istanbul",
    "Europe/Kiev",
    "Europe/Kiev",
    "Europe/Kiev",
    "Europe/Kiev",
    "Europe/Rome",
    "Europe/Berlin"
  )
)


setDT(tz_table)
setnames(tz_table, colnames(tz_table), toupper(colnames(tz_table)))
full_mappings = copy(tz_table)
# save the package data in the correct format
usethis::use_data(full_mappings, overwrite = TRUE)

# country_mappings = full_mappings[
#   ZONE %in% c(
#     'AL', 'AT', 'BY', 'BE', 'BA', 'BG', 'HR', 'CY', 'CZ', 'DE_LU', 'DK_1', 'DK_2', 'EE',
#     'FI', 'FR', 'DE', 'GR', 'HU', 'IS', 'IE', 'IT', 'IT_CALA', 'IT_SUD', 'IT_SICI', 'IT_SARD',
#     'IT_CSUD', 'IT_CNOR', 'IT_NORD', 'LV', 'LT', 'LU', 'MT', 'ME', 'UK', 'GE', 'NL', 'NO_1',
#     'NO_2', 'NO_3', 'NO_4', 'NO_5', 'NO', 'PL', 'PT', 'RO', 'MD', 'RU', 'SE', ''
#   )
# ]
